// <auto-generated />
using GP.SS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace GP.SS.Database.Migrations
{
    [DbContext(typeof(SaldeoSynchronizatorContext))]
    [Migration("20190716145137_CreateContratorsTable")]
    partial class CreateContratorsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("GP.SS.Domain.Company", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("CompanyProgramId");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("Postcode");

                    b.Property<string>("ShortName");

                    b.Property<string>("Street");

                    b.Property<string>("Telephone");

                    b.Property<string>("Username");

                    b.Property<string>("VatNumber");

                    b.HasKey("Id");

                    b.ToTable("Saldeo.Companies");
                });

            modelBuilder.Entity("GP.SS.Domain.Contractor", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("CompanyId");

                    b.Property<string>("ContractorProgramId");

                    b.Property<string>("Emails");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsCustomer");

                    b.Property<bool>("IsSupplier");

                    b.Property<string>("Postcode");

                    b.Property<string>("ShortName");

                    b.Property<string>("Street");

                    b.Property<string>("Telephone");

                    b.Property<string>("VatNumber");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Saldeo.Contractors");
                });

            modelBuilder.Entity("GP.SS.Domain.Contractor", b =>
                {
                    b.HasOne("GP.SS.Domain.Company", "Company")
                        .WithMany("Contractors")
                        .HasForeignKey("CompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
