// <auto-generated />
using GP.SS.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace GP.SS.Database.Migrations
{
    [DbContext(typeof(SaldeoSynchronizatorContext))]
    partial class SaldeoSynchronizatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("GP.SS.Domain.Company", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("CompanyProgramId");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("Postcode");

                    b.Property<string>("ShortName");

                    b.Property<string>("Street");

                    b.Property<string>("Telephone");

                    b.Property<string>("Username");

                    b.Property<string>("VatNumber");

                    b.HasKey("Id");

                    b.ToTable("Saldeo.Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
